### ISSUE TITLE
Osx

### ISSUE THREAD

**Issue by arterror** [handcraftedcc/SDFModeler#1]
Can't click on any items in the toolbar, each item respond (and they don't have any icon) " Cannot find the tool dom::SDFM_VolumePrim" for example ...
and there is no script in the button, is it normal ?

![Screenshot 2023-11-13 at 15 49 33](https://github.com/handcraftedcc/SDFModeler/assets/4596290/93afde19-06a9-4131-9f9f-72377d3d23e4)
![Screenshot 2023-11-13 at 15 49 40](https://github.com/handcraftedcc/SDFModeler/assets/4596290/a5ba1829-375c-4b00-aa25-e939a2c0f982)
![Screenshot 2023-11-13 at 15 51 06](https://github.com/handcraftedcc/SDFModeler/assets/4596290/77576882-3c0a-4d4c-976e-f978712008a1)

**Comment by handcraftedcc** [comment]
Do the nodes show up in the tab menu if you type sdfm?

**Comment by handcraftedcc** [comment]
It looks like something did not go correctly on the installation. It looks like the toolbar installed but not the actual nodes. Did you unpack everything including the otl folder and set it up correctly via the .json file?

**Comment by arterror** [comment]
![Screenshot 2023-11-13 at 16 07 43](https://github.com/handcraftedcc/SDFModeler/assets/4596290/1b70b15a-9619-4e3a-82ad-27ce54f76e19)

yes the node are here in the tab menu and they work

**Comment by arterror** [comment]
_Did you unpack everything including the otl folder and set it up correctly via the .json file?_
yes of couse

**Comment by handcraftedcc** [comment]
Okay good! I'm glad the other stuff is working fine!
Let me test the toolbar on my end.

**Comment by handcraftedcc** [comment]
I was able to reproduce the issue on h20 for me!
I went ahead and removed the toolbar for now.
It's super easy to make your own if that's something you want (make a new custom toolbar, and just drag the nodes onto it), but the old setup also doubled up the items that appeared under the tab menu which might be confusing.

**Comment by handcraftedcc** [comment]
I did go ahead and add a radial menu! If you go into your radial menu settings you should see the SDFM radial menu and you can add a shortcut for it (in my case I have a bunch of radial menus under ctrl+shift+1 etc.
I have found that the radial menu is an amazing way to quickly work with the SDFM toolset!

**Comment by arterror** [comment]
![Screenshot 2023-11-14 at 11 14 09](https://github.com/handcraftedcc/SDFModeler/assets/4596290/587afa60-6dee-419e-88d2-61f188fa0676)
![Screenshot 2023-11-14 at 11 27 02](https://github.com/handcraftedcc/SDFModeler/assets/4596290/bcc94b49-29e3-4a0e-8d1e-4dbdf55ddd4c)

Working Nice, now I'll try to understand how all that is working, the only strange thing in the radial menu is SDFM Assembler and SDFM Prim don't have any icons and don't load, but it is not a big problem anyway, Tx for the guidance

![Screenshot 2023-11-14 at 11 33 43](https://github.com/handcraftedcc/SDFModeler/assets/4596290/6f098e6b-3f4a-4a46-9337-cf04a7a54fa6)
![Screenshot 2023-11-14 at 11 33 28](https://github.com/handcraftedcc/SDFModeler/assets/4596290/2eb92fb4-ca8e-4636-a2d0-8beb76e2a08b)

A last thing is it possible to have the radial in the viewport instead ?

**Comment by handcraftedcc** [comment]
Figured out the issue. The radial menu has to be update each time I create a new version of the node!
Latest update also fixes that!

As regards to the viewport, I don't think that will be possible, since the nodes are not added underneath, but in various locations in the node tree!

**Comment by arterror** [comment]
I fixed it with your instruction, working and icon is back
![Screenshot 2023-11-14 at 18 48 54](https://github.com/handcraftedcc/SDFModeler/assets/4596290/2e7833a4-7ab8-4085-bc47-f690285a4574)
