### ISSUE TITLE
Only in non-commercial mode? Really?

### ISSUE THREAD

**Issue by MentalBase** [handcraftedcc/SDFModeler#2]
![image](https://github.com/handcraftedcc/SDFModeler/assets/69431567/8a09f3b6-d427-4385-b141-42c48addd4b1)
Is modeller available only for apprentice and free users? It asks to switch Houdini to non-com verion so i can use it. Like why in a world...

**Comment by handcraftedcc** [comment]
This is because I only have Houdini Indie. By default assets created in Indie can only be used in other Indie or Apprentice versions. I had to have the assets converted for fx and core use!

**Comment by MentalBase** [comment]
Oh, forgive my stupidity, now i see. Modeller by itself is good, thank you for your time and effort!

Feature request: Boolean volume modeling is twice cooler with tools like [Boxcutter](https://www.sidefx.com/docs/houdini/nodes/sop/labs--boxcutter.html) [(Blender analog).](https://www.youtube.com/watch?v=odb8-78YgBk). It would be a killer to have a SDFmodeller node with that possibilities since labs version doesn't work good. That feature will make your product top modeling tool for Houdini!
