### ISSUE TITLE
Houdini 20.05 support

### ISSUE THREAD

**Issue by mentalhub** [handcraftedcc/SDFModeler#3]
Hello mates.
Any updates for Houdini 20.05?

**Comment by handcraftedcc** [comment]
Have you encountered any issues on 20.5?

**Comment by mentalhub** [comment]
Sorry, its all good now. It would be useful to mention that modeller folder cannot be places in <Path>/houdini20.5/ folder alongside package folder, you need at least subfolder or place it anywhere else on your file system. Thanks.
